### ISSUE TITLE
No GPS Signal found

### ISSUE THREAD

**Issue by Spankplank** [RomanTheLegend/Pokemon_NoGo#3]
Hi, i'm new here so i'm not realy sure if this is the right spot for this.
But here s the problem i have:

I have followed the read-me very closely and the only step i skipped was this one:
![image](https://cloud.githubusercontent.com/assets/20791955/17324677/f05a207a-58a7-11e6-9b08-2e57917cb3e9.png)

I skipped that step because it looked like the namechance allready worked (when i go in file manager i see this:
![image](https://cloud.githubusercontent.com/assets/20791955/17324747/2eaa64c0-58a8-11e6-962d-90007a0dfb61.png)
)

and the last thing i m unsure about is how i should launch Pokemon GO while Pokemon NO GO is running. so far i did this:
https://gyazo.com/e3a7873a47c59617cf247743a689832f

the final result is this:
![image](https://cloud.githubusercontent.com/assets/20791955/17324915/2f927660-58a9-11e6-949d-61785fb5aac9.png)

I hope i have explained my problem good enough.
and look forward to an answer.

Greetings

**Comment by RomanTheLegend** [comment]
Hello,

I suspect  because this is NOX with preinstalled pokemons and own game control components it could be conflicting with the code.

Please either try clean version of NOX or alternatively replace NOX VM image with this one:
https://goo.gl/x5RiK1

it has everything configured and ready to  go. Instructions are inside

**Comment by Spankplank** [comment]
Thanks for the quick respons.
I did as you told but there is still something wrong.
the GPS signal is found i guess .. But i can't move or teleport to a location.

![image](https://cloud.githubusercontent.com/assets/20791955/17337962/745641dc-58e5-11e6-88e7-8b410b7bdf04.png)

this is what is happening now
i tried installing an older version of the game but that didn't help either

i look forward to another answer that makes me put another step in the right direction :)
Greetings

**Comment by RomanTheLegend** [comment]
Ok, so it's teleported to the default location which is that parking lot. You're on a good track. 

Now check in Android status bar Pokemon NoGo client status - it should be "Client connected"

![screenshot](https://s31.postimg.org/s18rjhrwb/Capture.png)

If it's not - restart ADB connection and then restart Ashburn. Once done, try teleporting here:

Latitude: 52.520007
Longitude: 13.404954

**Comment by Spankplank** [comment]
once again, thanks for the quick response.
Android statusbar sais what it should say tho ..
![image](https://cloud.githubusercontent.com/assets/20791955/17343133/7d7f9b7a-58fc-11e6-80f1-0dd29459b6bb.png)

but still, i can't teleport :/

**Comment by RomanTheLegend** [comment]
Please try to reinstall NOX player, but this time get a clean version without Pokemon GO preinstalled and then unpack NOX VM from the archive provided:
https://goo.gl/x5RiK1

**Comment by RomanTheLegend** [comment]
I strongly suspect that NOX with Pokemon preinstalled has some extra system calls & hooks which are getting in the way

**Comment by RomanTheLegend** [comment]
Looks like something has changed in Pokemon version 31. Versions 29.1 and 29.2 used to work fine, but 31 indeed rejects GPS. Will investigate this further

**Comment by nicolasdalsass** [comment]
Can confirm, worked on previous versions, but not on 31.

**Comment by RomanTheLegend** [comment]
Good news guys! I fixed GPS issue and preparing new build & NOX VM image with client version 0.31

Sources are pushed and instructions are updated on Main page. For the time being Pokemon Detector doesn't work because I didn't update the API yet

**Comment by RomanTheLegend** [comment]
NOX VM with Pokemon GO v0.31 and all necessary things installed:

https://goo.gl/TOCZjy

Sorry for the late, I had some problems with internet over these few days
